name: Terraform Infrastructure & App Installation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  terraform-infra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [gcp-vm-creation]

    env:
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure GCP Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Terraform Init
        working-directory: ${{ matrix.project }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ matrix.project }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ${{ matrix.project }}
        run: terraform apply tfplan
